#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"@(#)Makefile	1.6	09/06/24 SMI"
#

STF_DONTBUILDMODES=true
STF_BUILD_SUBDIRS=test00 test01 test02 test03 test04 test05 test06 test07 test08 \
		  test09 test10 test11 test12 test13 test14
STF_EXECUTE_SUBDIRS=${STF_BUILD_SUBDIRS}

include ${STF_TOOLS}/Makefiles/Makefile.master
