#!/usr/bin/ksh -p
#
# Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"@(#)checkenv_def	1.1	08/04/22 SMI"
#

. ${STF_SUITE}/include/checkenv.kshlib

TASK=$1

if [ $TASK == "CONFIGURE" ] || [ $TASK == "EXECUTE" ]; then
        ce_interface_exist $TST_INT $TST_NUM; save_results $?
fi
