#!/usr/bin/ksh -p
#
# Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"@(#)Makefile	1.1	08/04/22 SMI"
#

STF_ROOT_TESTCASES=runme
STF_EXECUTABLES=dr.auto
STF_ENVFILES=timeout.env
STF_ROOT_CHECKENV=checkenv_def
STF_DONTBUILDMODES=true

include ${STF_TOOLS}/Makefiles/Makefile.master

